# -----------------------------------------------------------------------------
# Home Page
# -----------------------------------------------------------------------------

kiwi_saver_cal                    = "/kiwisaver/calculators/"
get_started_button                = "xpath=//a[contains(text(),'Click here to get started.')]"
kiwi_save_retirement_cal          = "xpath=//h1[contains(text(),'KiwiSaver Retirement Calculator')]"
kiwi_saver_current_age            = "xpath=//div[contains(@help-id,'CurrentAge')]/button/i"
kiwi_saver_employment_status      = "xpath=//div[contains(@help-id,'EmploymentStatus')]/button/i"
kiwi_saver_current_balance        = "xpath=//div[contains(@help-id,'KiwiSaverBalance')]/button/i"
kiwi_saver_vol_contribution       = "xpath=//div[contains(@help-id,'VoluntaryContributions')]/button/i"
kiwi_saver_Risk_Profile           = "xpath=//div[contains(@help-id,'RiskProfile')]/button/i"
kiwi_saver_Savings_Goal           = "xpath=//div[contains(@help-id,'SavingsGoal')]/button/i"
kiwi_saver_age_calculator_msg     = "xpath=//div/p[contains(text(),'This calculator has an age limit of 18 to 64 years old')]"
kiwi_saver_iframe                 = "xpath=//*[@id='calculator-embed']/iframe"
current_age_input                 = "xpath=//div[1][contains(@model,'CurrentAge')]/div/div/div/input"
employment_status_input           = "xpath=//div[contains(@selected-content,'EmploymentStatus')]/div/div[contains(@class,'control-well')]"
employment_status_employed        = "xpath=//ul/li[2]/div/span"
employment_status_self_employed   = "xpath=//ul/li[3]/div/span"
employment_status_not_employed    = "xpath=//ul/li[4]/div/span"
salary_wage_per_year_input        = "xpath=//div[1][contains(@model,'AnnualIncome')]/div/div/div/input"
kiwi_saver_member_contibution     = "xpath=//span/input[contains(@id,'radio-option-04F')]"
risk_profile_defensive            = "xpath=//input[contains(@Id,'radio-option-013')]"
retierment_projection_button      = "xpath=//button/span[contains(text(),'View your KiwiSaver retirement projections')]"
kiwi_saver_balance_input          = "xpath=//div[1][contains(@model,'KiwiSaverBalance')]/div/div/div/input"
voluntary_contribution            = "xpath=//div[1][contains(@model,'VoluntaryContributions')]/div/div/div/input"
frequecy_for_contibution          = "xpath=//div[contains(@class,'well-value ng-binding')]/span[contains(text(),'Frequency')]"
risk_profile_conservative         = "xpath=//input[contains(@Id,'radio-option-016')]"
frequecy_for_fortnightly          = "xpath=//div/span[contains(text(),'Fortnightly')]"
Saving_goal_at_retirement         = "xpath=//div[1][contains(@model,'SavingsGoal')]/div/div/div/input"
frequecy_for_annually             = "xpath=//div/span[contains(text(),'Annually')]"
risk_profile_balanced             = "xpath=//input[contains(@Id,'radio-option-019')]"